# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-23 06:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('math_score', models.IntegerField(default=0)),
                ('english_score', models.IntegerField(default=0)),
                ('physics_score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2048)),
                ('age', models.IntegerField(default=18)),
                ('sex', models.BooleanField(default=False)),
                ('hobby', models.CharField(max_length=4096)),
            ],
        ),
        migrations.AddField(
            model_name='score',
            name='student_managment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_managment.Student'),
        ),
    ]
